name: Update Submodule

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout parent repo
        uses: actions/checkout@v2
        with:
          submodules: true  # Ensure submodules are checked out
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Update submodule
        run: |
          set -x  # Enable debug logging
          git checkout -b update-submodule
          git submodule update --remote --merge
          git status
          git diff
          git add .
          git status
          git commit -m "Update submodule to latest commit" || echo "Nothing to commit"

      - name: Push changes
        if: success() && steps.update.outputs.changes == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin update-submodule

      - name: Create Pull Request
        if: success() && steps.update.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Update submodule"
          body: "This PR updates the submodule to the latest commit."
          branch: "update-submodule"
